name: Metrics
on:
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: base.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: activity, community, repositories, metadata
          base_indepth: yes

      - uses: lowlighter/metrics@latest
        with:
          filename: languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          base_indepth: yes
          plugin_languages: yes
          plugin_languages_analysis_timeout: 360
          plugin_languages_analysis_timeout_repositories: 15
          plugin_languages_indepth: yes
          plugin_languages_sections: most-used
          plugin_languages_skipped: wedding, bi-doc
          plugin_languages_ignored: html, css, roff, digital command language
          plugin_languages_limit: 5
          # plugin_languages_recent_days: 30
          plugin_languages_details: lines, bytes-size, percentage
          commits_authoring: Jiacheng Wang, jcwang587, jiachengwang@umass.edu
